language: php
php:
- 7.0
- 5.6
before_script:
- cp .env.example .env
- composer self-update
- composer install --prefer-source --no-interaction
- php artisan key:generate
- touch database/database.sqlite
- php artisan migrate
script:
- "./vendor/bin/phpunit"

